services:
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_SENTRY_DSN=${CLIENT_SENTRY_DSN}
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - "3000:3000"

  server:
    restart: unless-stopped
    build:
      context: ./service
      dockerfile: Dockerfile
    environment:
        - SERVICE_DB_URL=${SERVICE_DB_URL}
        - SERVICE_DB_LOGIN=${SERVICE_DB_LOGIN}
        - SERVICE_DB_PASSWORD=${SERVICE_DB_PASSWORD}
        - SERVICE_SENTRY_DSN=${SERVICE_SENTRY_DSN}
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb

  mysqldb:
    build:
      context: ./service/db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${SERVICE_DB_PASSWORD}
      MYSQL_USER: ${SERVICE_DB_LOGIN}
      MYSQL_PASSWORD: ${SERVICE_DB_PASSWORD}
      MYSQL_DATABASE: ${SERVICE_DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  default:
    name: isusosdown-network
    external: true